## Assignment: Caching the Inverse of a Matrix
## The below functions are used to create a special object that stores a matrix and chaches its inverse.

## makeCacheMatrix function creates a special matrix object and caches its inverse.

makeCacheMatrix <- function(x = matrix()) {
        inv <- NULL
        set <- function(y){
                x <<- y
                inv <<- NULL
        }
        get <- function()x
        setInverse <- function(inverse) inv <<- inverse
        getInverse <- function() inv
        list(set = set, get = get, setInverse = setInverse, getInverse = getInverse)
}


## cacheSolve function computes the inverse of the "matrix" generated by the makeCacheMatrix function.
## This function first checks if the inverse has already been calculated, then retrieves the inverse from cache.

cacheSolve <- function(x, ...) {
        ## Return a matrix that is the inverse of 'x'
        inv <- x$getInverse()
        if(!is.null()){
                message("Getting cached data.")
                return(inv)
        }
        matr <- x$get()
        inv <- solve(matr, ...)
        x$setInverse(inv)
        inv
}
