## Assignment: Caching the Inverse of a Matrix
## The below functions are used to create a special object that stores a matrix and chaches its inverse.

## makeCacheMatrix function creates a special matrix object and caches its inverse.
## This function contains the ff. functions:
##      setMatrix       sets the matrix value
##      getMatrix       gets the matrix value
##      setInverse      sets the inversed matrix (caches the inverse of the matrix)
##      getInverse      gets the inversed matrix value

makeCacheMatrix <- function(x = matrix()) {
        inv <- NULL
        setMatrix <- function(y){
                x <<- y
                inv <<- NULL
        }
        getMatrix <- function()x
        setInverse <- function(inverse) inv <<- inverse
        getInverse <- function() inv
        list(setMatrix = setMatrix, getMatrix = getMatrix, setInverse = setInverse, getInverse = getInverse)
}


## cacheSolve function computes the inverse of the "matrix" generated by the makeCacheMatrix function.
## This function first checks if the inverse has already been calculated, then retrieves the inverse from cache.

cacheSolve <- function(x, ...) {
        ## Return a matrix that is the inverse of 'x'
        inv <- x$getInverse()
        if(!is.null(inv)){
                message("Getting cached data.")
                return(inv)
        }
        matr <- x$getMatrix()
        inv <- solve(matr, ...)
        x$setInverse(inv)
        inv
}
